stages:
  - build
  - test

image: node:12-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - dist/
    - coverage/

build:
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - develop

test:
  stage: test
  script:
    - npm run test-ci
  only:
    - develop
  coverage: /All files\s*\|\s*([\d\.]+)/
