stages:
  - build
  - test

image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - dist/

build:
  stage: build
  script:
    - curl https://apihomefood.herokuapp.com
    - npm install
    - npm run build
  only:
    - develop

test:
  stage: test
  script:
    - npm run test
  only:
    - develop
